---
title: "4b"
output: html_document
date: "2023-06-22"
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r libraries}
require("dplyr")
require("tidyr")
require("tidyverse")
require("readxl")
require("readr")
require("tibble")
require("xlsx")
require("ggplot2")
require("purrr")
require("reshape2")
require("broom")
require("gridExtra")
require("survival")
require("ggfortify")
require("ggrepel")
require("survminer")
require("contsurvplot")

save.data = T
save.plots = T

set.seed(123)
```

```{r importing data files}
annotation <- read.delim("data/proteinGroups_annotated.txt")
raw_data <- read_excel("output_files/data/4a_mice_data.xlsx")
```


```{r creating required variables for cox}
set.seed(123)

annotation <- annotation[-1, ]                                                  #cleaning annotation file

event_data <- raw_data %>%
  mutate(event_all = if_else(is.na(Days_to_heal), 0, 1),                        #creating "event" variable
         #Days_to_heal_180 = tidyr::replace_na(Days_to_heal, 180),        
          Days_to_heal_cox = replace(Days_to_heal, 
                                     is.na(Days_to_heal),                       #replacing NA values with random value
                                     sample(seq(180, 250, 1),                   #between 180 and 250
                                            sum(is.na(Days_to_heal)), 
                                            replace = TRUE)),
         .before="A0A024R0T9;K7ER74;P02655;Q6P163;V9GYJ8") %>% 
  dplyr::select(-Days_to_heal)

protein_names_cox <- names(event_data[-c(1:13)])      #8                          #list of protein names

listOfModels_cox <- vector("list", length(protein_names_cox))                   #empty vector for models

# Add survival object(status == 2 is death)
event_data <- event_data %>%                                                    #survival object
  mutate(SurvObj = with(event_data, 
                        Surv(Days_to_heal_cox, event_all)),#, event_all)),
         .before="A0A024R0T9;K7ER74;P02655;Q6P163;V9GYJ8")
```

```{r cox}
results_cox = data.frame()

# loop over features
for (i in 1:length(protein_names_cox)) {
  
  fml <- paste0("SurvObj~`",protein_names_cox[i],"`+Age+Gender+Triglyceride+Diabetes_Type+Diabetes_Duration+HBA1C+BMI")
  
  currentModel <- coxph(formula = as.formula(fml), data = event_data)
  
  listOfModels_cox[[i]] <- currentModel 
  
  results_cox = rbind(results_cox, currentModel %>% tidy(conf.int = T) %>% slice(1))
  
} 
```

```{r fdr correction}
results_cox[1] <- lapply(results_cox[1], gsub, pattern = "`", replacement = "")
results_cox_adjusted <- mutate(results_cox, p.value.adjusted = p.adjust(results_cox$p.value, method = "fdr"))

results_cox_adjusted <- results_cox_adjusted %>% 
  #filter(p.value.adjusted<0.05) %>% 
  left_join(annotation, by = join_by('term' == 'Protein.IDs')) %>% 
  dplyr::select(c(term, estimate, std.error, statistic, p.value,p.value.adjusted, conf.low, conf.high, Protein.name, Protein.names, Gene.name, Gene.names, UniProt.names, PDB, KEGG, KEGG.name, GOBP, GOBP.name))

results_cox_adjusted <- results_cox_adjusted %>%
  mutate(UniProt.names = ifelse(term == "P0DOY2", "IGLC2_HUMAN", UniProt.names))
 
#results_cox_adjusted <- results_cox_adjusted %>%
 # mutate(across(Protein.name:GOBP.name, ~ ifelse(term == "P0DOY2", "IGLC2_", .)))

```

```{r saving xlsx}

if(save.data) write.xlsx(as.data.frame(results_cox_adjusted), 
                         "output_files/data/4b_cox_adjusted.xlsx", 
                         row.names = FALSE)

results_cox_filtered <- results_cox_adjusted %>% 
  filter(p.value.adjusted<0.1)

uniprot_names <- data.frame()
uniprot_names <- results_cox_filtered %>% 
  #mutate(Protein_name = str_extract(UniProt.names,"[^_]+")) %>% 
  dplyr::select(c(Gene.name, estimate, std.error, statistic, p.value, p.value.adjusted, conf.low, conf.high))

if(save.data) write.xlsx(as.data.frame(uniprot_names), 
                         "output_files/data/4b_cox_adjusted_uniprotnames.xlsx", 
                         row.names = FALSE)
  
```

```{r volcano plot}
# https://ab604.github.io/docs/bspr_workshop_2018/transform.html#volcano-plot

plot <- ggplot(results_cox_adjusted, aes(x = exp(estimate), y = -log10(p.value.adjusted))) +
  geom_point(aes(color="grey", 
                 alpha=0.4,
                 size = -log10(p.value.adjusted)))  +
  ggtitle("Volcano plot for cox survival analysis estimates") +
  xlab("Hazard ratio") + 
  ylab(expression("-log"[10]*"(p-value)")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = rel(1.5), 
                                  hjust = 0, 
                                  margin = margin(b = 10))) +
    geom_text_repel(data=results_cox_filtered,
                    aes(x = exp(estimate), 
                        y = -log10(p.value.adjusted),
                        label=str_extract(UniProt.names,"[^_]+"),
                        point.size = -log10(p.value.adjusted)),
                    size=2.5, 
                    point.padding = 0,
                    #min.segment.length = 0,
                    max.time = 3, max.iter = 1e6,
                    box.padding = 0.3,
                    max.overlaps = 20) +
  geom_point(data=results_cox_filtered,
             aes(x = exp(estimate), 
                 y = -log10(p.value.adjusted),
                 color="red",
                 alpha=0.4,
                 size = -log10(p.value.adjusted))) +
  scale_color_manual(values=c('gray','red')) + 
  geom_vline(xintercept = 1, linetype = "dotted")+ 
  #xlim(c(-.5, .5)) + 
         scale_color_manual(labels = c("None", expression("P"[FDR]*"< 0.10")), 
                     values = c("grey", "red"))+ 
  labs(color = "Significance") +
  guides(color = guide_legend(title = "Significance"),
         alpha = FALSE,  # Remove the alpha legend
         size = FALSE)   # Remove the size legend

if(save.plots) ggsave(plot, 
                      filename = "output_files/figures/4b/volcano_plot.png",
                      width = 10, 
                      height = 7, 
                      device='tiff', 
                      dpi=700)
```


```{r KM survival curves - covariates}
# https://en.wikipedia.org/wiki/Survival_analysis
# https://rviews.rstudio.com/2017/09/25/survival-analysis-with-r/

# add method to grid.draw
grid.draw.ggsurvplot <- function(x){
  survminer:::print.ggsurvplot(x, newpage = FALSE)
}

# All

fit <- survfit(event_data$SurvObj ~ 1, data=event_data) 

if(save.data) sink("output_files/figures/4b/fit_summary_all.txt")
print(summary(fit, times = c(1,5*(1:40))))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ 1, data=event_data))
sink()

plot <- ggsurvplot(fit,
                   fun = 'event',
                   conf.int=TRUE, 
                   pval=TRUE,
                   pval.coord=c(200,0.2), 
                   risk.table=TRUE,
                   cumevents=TRUE, 
           #legend.labs=c("Type 1", "Type 2"), 
           #legend.title="Diabetes type",  
           palette=c("dodgerblue2", "orchid2"), 
           title="Kaplan-Meier Curve for DFU healing", 
           xlab="Time in days",
           ylab="Probability of healing (%)",
           risk.table.height=.15,
           risk.table.title="Number of potentially healing subjects",
           cumevents.height=.15,
           cumevents.title="Cumulative number of healed subjects")

if(save.plots) ggsave(plot, 
                      filename = "output_files/figures/4b/KM_curve_all.png",
                      width = 10, 
                      height = 10, 
                      device='tiff', 
                      dpi=700)

# Diabetes type

fit <- survfit(event_data$SurvObj ~ Diabetes_Type, data=event_data) 

if(save.data) sink("output_files/figures/4b/fit_summary_Dtype.txt")
print(summary(fit, times = c(1,5*(1:40))))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ Diabetes_Type, data=event_data))
sink()

plot <- ggsurvplot(fit,
                   fun = 'event',
                   conf.int=TRUE, 
                   pval=TRUE,
                   pval.coord=c(200,0.2),
                   risk.table=TRUE,
                   cumevents=TRUE,
           legend.labs=c("Type 1", "Type 2"), 
           legend.title="Diabetes type",  
           palette=c("dodgerblue2", "orchid2"), 
           title="Kaplan-Meier Curve for DFU healing [Diabetes Type]",
           xlab="Time in days",
           ylab="Probability of healing (%)",
           risk.table.height=.15,
           risk.table.title="Number of potentially healing subjects",
           cumevents.height=.15,
           cumevents.title="Cumulative number of healed subjects")

if(save.plots) ggsave(file = "output_files/figures/4b/KM_curve_Dtype.png",
                      plot,
                      width = 10,
                      height = 10,
                      device='tiff',
                      dpi=700)

# Gender

fit <- survfit(event_data$SurvObj ~ Gender, data=event_data) 

if(save.data) sink("output_files/figures/4b/fit_summary_gender.txt")
print(summary(fit, times = c(1,5*(1:40))))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ Gender, data=event_data))
sink()

plot <- ggsurvplot(fit,
                   fun = 'event',
                   conf.int=TRUE, 
                   pval=TRUE,
                   pval.coord=c(200,0.2),
                   risk.table=TRUE,
                   cumevents=TRUE,
           legend.labs=c("Male", "Female"), 
           legend.title="Gender",  
           palette=c("dodgerblue2", "orchid2"), 
           title="Kaplan-Meier Curve for DFU healing [Gender]",
           xlab="Time in days",
           ylab="Probability of healing (%)",
           risk.table.height=.15,
           risk.table.title="Number of potentially healing subjects",
           cumevents.height=.15,
           cumevents.title="Cumulative number of healed subjects")

if(save.plots) ggsave(file = "output_files/figures/4b/KM_curve_gender.png",
                      plot,
                      width = 10,
                      height = 10,
                      device='tiff',
                      dpi=700)
```

```{r KM survival contours - covariates}
# Diabetes duration

fit <- coxph(Surv(Days_to_heal_cox) ~ Diabetes_Duration, data=event_data, x=TRUE)
pvalue <- round(summary(fit)$coefficients[, 5], digits = 2)

if(save.data) sink("output_files/figures/4b/fit_summary_Dduration.txt")
print(survfit(event_data$SurvObj ~ Diabetes_Duration, data=event_data))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ Diabetes_Duration, data=event_data))
sink()

plot <- plot_surv_contour(time="Days_to_heal_cox",
                  status="event_all",
               variable="Diabetes_Duration",
               data=event_data,
               model=fit,
               fun = "event",
               title="Survival Probability Contour Curve for DFU Healing [Diabetes Duration]",
               legend.title="Probability of not healing",
               xlab="Time (days)",
               ylab="Diabetes duration (years)") + 
  annotate("text", x = -Inf, y = -Inf,
           vjust = -2, hjust = -1, 
           label = paste0("p = ",pvalue))

if(save.plots)ggsave(file = "output_files/figures/4b/KM_curve_Dduration.png",
                      plot,
                      width = 10,
                      height = 7,
                      device='tiff',
                      dpi=700)

# BMI

fit <- coxph(Surv(Days_to_heal_cox) ~ BMI, data=event_data, x=TRUE)
pvalue <- round(summary(fit)$coefficients[, 5], digits = 2)

if(save.data) sink("output_files/figures/4b/fit_summary_bmi.txt")
print(survfit(event_data$SurvObj ~ BMI, data=event_data))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ BMI, data=event_data))
sink()

plot <- plot_surv_contour(time="Days_to_heal_cox",
                  status="event_all",
               variable="BMI",
               data=event_data,
               model=fit,
               title="Survival Probability Contour Curve for DFU Healing [BMI]",
               legend.title="Probability of not healing",
               xlab="Time (days)",
               ylab="Body Mass Index (BMI)") + 
  annotate("text", x = -Inf, y = -Inf,
           vjust = -2, hjust = -1, 
           label = paste0("p = ",pvalue))

if(save.plots) ggsave(file = "output_files/figures/4b/KM_curve_bmi.png",
                      plot,
                      width = 10,
                      height = 7,
                      device='tiff',
                      dpi=700)

# age

fit <- coxph(Surv(Days_to_heal_cox) ~ Age, data=event_data, x=TRUE)
pvalue <- round(summary(fit)$coefficients[, 5], digits = 2)

if(save.data) sink("output_files/figures/4b/fit_summary_age.txt")
print(survfit(event_data$SurvObj ~ Age, data=event_data))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ Age, data=event_data))
sink()

plot <- plot_surv_contour(time="Days_to_heal_cox",
                  status="event_all",
               variable="Age",
               data=event_data,
               model=fit,
               title="Survival Probability Contour Curve for DFU Healing [Age]",
               legend.title="Probability of not healing",
               xlab="Time (days)",
               ylab="Age (years)") + 
  annotate("text", x = -Inf, y = -Inf,
           vjust = -2, hjust = -1, 
           label = paste0("p = ",pvalue))

if(save.plots) ggsave(file = "output_files/figures/4b/KM_curve_age.png",
                      plot,
                      width = 10,
                      height = 7,
                      device='tiff',
                      dpi=700)

# hba1c

fit <- coxph(Surv(Days_to_heal_cox) ~ HBA1C, data=event_data, x=TRUE)
pvalue <- round(summary(fit)$coefficients[, 5], digits = 2)

if(save.data) sink("output_files/figures/4b/fit_summary_HBA1C.txt")
print(survfit(event_data$SurvObj ~ HBA1C, data=event_data))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ HBA1C, data=event_data))
sink()

plot <- plot_surv_contour(time="Days_to_heal_cox",
                  status="event_all",
               variable="HBA1C",
               data=event_data,
               model=fit,
               title="Survival Probability Contour Curve for DFU Healing [HBA1C]",
               legend.title="Probability of not healing",
               xlab="Time (days)",
               ylab="HBA1C measure (mmol/mol)") + 
  annotate("text", x = -Inf, y = -Inf,
           vjust = -2, hjust = -1, 
           label = paste0("p = ",pvalue))

if(save.plots) ggsave(file = "output_files/figures/4b/KM_curve_HBA1C.png",
                      plot,
                      width = 10,
                      height = 7,
                      device='tiff',
                      dpi=700)

# Triglycerides

fit <- coxph(Surv(Days_to_heal_cox) ~ Triglyceride, data=event_data, x=TRUE)
pvalue <- round(summary(fit)$coefficients[, 5], digits = 2)

if(save.data) sink("output_files/figures/4b/fit_summary_triglycerides.txt")
print(survfit(event_data$SurvObj ~ Triglyceride, data=event_data))
cat("\n")
print(coxph(Surv(Days_to_heal_cox) ~ Triglyceride, data=event_data))
sink()

plot <- plot_surv_contour(time="Days_to_heal_cox",
                  status="event_all",
               variable="Triglyceride",
               data=event_data,
               model=fit,
               title="Survival Probability Contour Curve for DFU Healing [Triglycerides]",
               legend.title="Probability of not healing",
               xlab="Time (days)",
               ylab="Triglyceride measure (mmol/l)") + 
  annotate("text", x = -Inf, y = -Inf,
           vjust = -2, hjust = -1, 
           label = paste0("p = ",pvalue))

if(save.plots) ggsave(file = "output_files/figures/4b/KM_curve_triglycerides.png",
                      plot,
                      width = 10,
                      height = 7,
                      device='tiff',
                      dpi=700)
```

```{r KM survival contours - proteins}



for (i in 1:nrow(results_cox_filtered)) {
  
  fml <- paste0("SurvObj~`",results_cox_filtered$term[i],"`+Age+Gender+Triglyceride+Diabetes_Type+Diabetes_Duration+HBA1C+BMI")
  
  fit <- coxph(formula = as.formula(fml), data=event_data, x=TRUE)
  pvalue <- round(results_cox_filtered$p.value.adjusted[i], digits = 3)
  
  
  if(save.data) sink(paste0("output_files/figures/4b/fit_summary_", 
                                      str_extract(results_cox_filtered$UniProt.names[i],"[^_]+"), ".txt"))
  print(summary(fit))
  sink()
  
  
  plot <- plot_surv_contour(time="Days_to_heal_cox",
                  status="event_all",
               variable=results_cox_filtered$term[i],
               data=event_data,
               model=fit,
               title=paste0("Survival Probability Contour Curve for DFU Healing [Protein -> ", 
                            str_extract(results_cox_filtered$UniProt.names[i],"[^_]+"), "]"),
               legend.title="Probability of not healing",
               xlab = "Time (days)",
               ylab = str_extract(results_cox_filtered$UniProt.names[i],"[^_]+")) + 
  annotate("text", x = -Inf, y = -Inf,
           vjust = -2, hjust = -1, 
           label = bquote("P"[FDR]*"="~ .(pvalue)),
           colour = "white")
  
  if(save.plots) ggsave(file = paste0("output_files/figures/4b/KM_curve_", 
                                      str_extract(results_cox_filtered$UniProt.names[i],"[^_]+"), ".png"),
                                      plot,
                                      width = 10,
                                      height = 7,
                                      device='tiff',
                                      dpi=700)
  
} 

```